name: NuGet publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.*.*
        
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Display build error
      if: failure()
      run: |
        echo "Build failed with exit code: ${{ steps.build.outputs.exit-code }}"
        echo "Check the logs for more information."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish Nuget Package
      uses: brandedoutcast/publish-nuget@v2.5.2  
      with:
       PROJECT_FILE_PATH: Plutonication/Plutonication.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
