name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Display build error
      if: failure()
      run: |
        echo "Build failed with exit code: ${{ steps.build.outputs.exit-code }}"
        echo "Check the logs for more information."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
