name: NUnit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.*.*
        
    - name: Change directory
      run: cd PlutonicationTests

    - name: Install dependencies
      run: dotnet restore
      
    - name: NUnit tests
      run: dotnet test PlutonicationTests.csproj

    - name: Display build error
      if: failure()
      run: |
        echo "Build failed with exit code: ${{ steps.build.outputs.exit-code }}"
        echo "Check the logs for more information."
